### ISSUE TITLE
Updating article problem

### ISSUE THREAD

**Issue by commercialsuicide** [krabradosty/pshkBlogAdmin#1]
Need to fix updating article problem

The bugs are:

- Image, image.alt, image.title fields
- Ckeditor

https://github.com/krabradosty/pshkBlogAdmin/commit/69b6ca9007dd5171d5dd388774bf650ec214f9c0
https://github.com/krabradosty/pshkBlogAdmin/commit/c743dfc01e128323338f240897f3c0ff9ef7abee

**Comment by krabradosty** [comment]
это ты себе повесил?

**Comment by commercialsuicide** [comment]
всей нашей необъятной програмтим. ишис - нормальная тема, мне нравится

**Comment by commercialsuicide** [comment]
**Updated**

Remaining bugs:

- Ckeditor binding

-  + img preview

**Comment by commercialsuicide** [comment]
Ckeditor replaced to textAngular

211015bd5acb766e02aa5ce816916c5453c79970

**Done**
