### ISSUE TITLE
Need to refactoring logging page

### ISSUE THREAD

**Issue by krabradosty** [krabradosty/pshkBlogAdmin#12]
Сейчас у нас страница отдельно от приложения. То ли ее засунуть в него надо, то ли нет.

**Comment by commercialsuicide** [comment]
Можно засунуть, но толку от этого немного. Если делать будет нечего, давай засунем

**Comment by SuperDuperPugach** [comment]
а приложение не будет качаться по несколько раз, есил в процессе тебя
разлогинет?

**Comment by commercialsuicide** [comment]
а почему тебя в процессе должно разлогинить? это не опционально? меня сейчас разлогинивает слишком часто, это не нормально

**Comment by krabradosty** [comment]
@commercialsuicide это потому что ты OSEL
